/**
 * @module constant:message
 * @version 1.0.0
 * @license (C) Insight
 */

export const MESSAGE = {

  //-----------------------------------------------------------------------------------------------
  // ! Window
  //-----------------------------------------------------------------------------------------------

  ADD_EXTERNAL_AUGMENTATION: 'ADD_EXTERNAL_AUGMENTATION',
  PROCESS_SERP_OVERLAY: 'PROCESS_SERP_OVERLAY',
  REMOVE_AUGMENTATION_SUCCESS: 'EDIT_AUGMENTATION_SUCCESS',
  REMOVE_HIDE_DOMAIN_OVERLAY: 'REMOVE_HIDE_DOMAIN_OVERLAY',
  REMOVE_SEARCHED_DOMAIN: 'REMOVE_SEARCHED_DOMAIN',
  TOGGLE_BLOCKED_DOMAIN: 'TOGGLE_BLOCKED_DOMAIN',
  TOGGLE_TRUSTED_DOMAIN: 'TOGGLE_TRUSTED_DOMAIN',
  TRIGGER_FRAME_SCROLL_LOG: 'TRIGGER_FRAME_SCROLL_LOG',
  TRIGGER_GUTTER_HOVEROPEN: 'TRIGGER_GUTTER_HOVEROPEN',
  TRIGGER_PUBLICATION_TIMER: 'TRIGGER_PUBLICATION_TIMER',
  TRIGGER_START_TRACK_TIMER: 'TRIGGER_START_TRACK_TIMER',
  TRIGGER_STOP_TRACK_TIMER: 'TRIGGER_STOP_TRACK_TIMER',
  TRIGGER_ENGINE_SYNC: 'TRIGGER_ENGINE_SYNC',

  //-----------------------------------------------------------------------------------------------
  // ! Sidebar
  //-----------------------------------------------------------------------------------------------

  ADD_LOCAL_AUGMENTATION: 'ADD_LOCAL_AUGMENTATION',
  DISABLE_SUGGESTED_AUGMENTATION: 'DISABLE_SUGGESTED_AUGMENTATION',
  EXTENSION_SHORT_URL_RECEIVED: 'EXTENSION_SHORT_URL_RECEIVED',
  GET_TAB_DOMAINS: 'GET_TAB_DOMAINS',
  HIDE_FRAME_OVERLAY: 'HIDE_FRAME_OVERLAY;',
  OPEN_NEW_TAB: 'OPEN_NEW_TAB',
  OPEN_PAGE: 'OPEN_PAGE',
  OPEN_SETTINGS_PAGE: 'OPEN_SETTINGS_PAGE',
  SEND_FRAME_INFO: 'SEND_FRAME_INFO',
  SEND_LOG_MESSAGE: 'SEND_LOG_MESSAGE',
  SET_TAB_DOMAINS: 'SET_TAB_DOMAINS',
  SWITCH_TO_TAB: 'SWITCH_TO_TAB',
  UPDATE_MY_BLOCK_LIST: 'UPDATE_MY_BLOCK_LIST',
  UPDATE_SIDEBAR_TABS: 'UPDATE_SIDEBAR_TABS',
  URL_UPDATED: 'URL_UPDATED',

  //-----------------------------------------------------------------------------------------------
  // ! Logging
  //-----------------------------------------------------------------------------------------------

  EXTENSION_AUGMENTATION_SAVE: 'EXTENSION_AUGMENTATION_SAVE',
  EXTENSION_AUTO_EXPAND: 'EXTENSION_AUTO_EXPAND',
  EXTENSION_BLOCKLIST_ADD_DOMAIN: 'EXTENSION_BLOCKLIST_ADD_DOMAIN',
  EXTENSION_BLOCKLIST_REMOVE_DOMAIN: 'EXTENSION_BLOCKLIST_REMOVE_DOMAIN',
  EXTENSION_SERP_FILTER_LINK_CLICKED: 'EXTENSION_SERP_FILTER_LINK_CLICKED',
  EXTENSION_SERP_FILTER_LOADED: 'EXTENSION_SERP_FILTER_LOADED',
  EXTENSION_SERP_LINK_CLICKED: 'EXTENSION_SERP_LINK_CLICKED',
  EXTENSION_SERP_LINK_HOVEROPEN: 'EXTENSION_SERP_LINK_HOVEROPEN',
  EXTENSION_SERP_LOADED: 'EXTENSION_SERP_LOADED',
  EXTENSION_SERP_SUBTAB_CLICKED: 'EXTENSION_SERP_SUBTAB_CLICKED',
  EXTENSION_SUBTAB_SCROLL: 'EXTENSION_SUBTAB_SCROLL',

} as const;